databases:
  - name: CarLeasedb
    plan: free
    databaseName: CarLease
    user: CarLease

services:
  - type: web
    plan: free
    name: CarLease
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn AutoM.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: CarLease
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4