databases:
  - name: AutoM
    plan: free
    databaseName: AutoM
    user: AutoM

services:
  - type: web
    plan: free
    name: AutoM
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn AutoM.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AutoM
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4