# Generated by Django 5.1.3 on 2024-12-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_car_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
