# Generated by Django 5.0.6 on 2024-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(),
        ),
    ]
