# Generated by Django 5.0.6 on 2024-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
