# Generated by Django 5.0.6 on 2024-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Available_for_testing',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='picurl',
            field=models.ImageField(upload_to='car_pics/'),
        ),
    ]
