# Generated by Django 5.0.6 on 2024-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_car_available_for_testing_alter_car_picurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='test_drive_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
