# Generated by Django 5.0.6 on 2024-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='pass@gmail.com', max_length=254)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
