# Generated by Django 5.0.6 on 2024-06-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_profile_alter_customer_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
